# N: Skipping acquire of configured file 'mysql-tools/binary-arm64/Packages' as repository 'http://repo.mysql.com/apt/debian bullseye InRelease' doesn't support architecture 'arm64'
# N: Skipping acquire of configured file 'mysql-8.0/binary-arm64/Packages' as repository 'http://repo.mysql.com/apt/debian bullseye InRelease' doesn't support architecture 'arm64'
# N: Skipping acquire of configured file 'mysql-apt-config/binary-arm64/Packages' as repository 'http://repo.mysql.com/apt/debian bullseye InRelease' doesn't support architecture 'arm64'
# E: Package 'mysql-server' has no installation candidate

FROM debian:bullseye-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update; \
    apt install -y --no-install-recommends bzip2 ca-certificates dirmngr gnupg locales lsb-release openssl perl wget xz-utils zstd

RUN sed -i -e 's/# ko_KR.UTF-8 UTF-8/ko_KR.UTF-8 UTF-8/' /etc/locale.gen; \
    echo 'LANG="ko_KR.UTF-8"' >> /etc/default/locale; \
    dpkg-reconfigure --frontend=noninteractive locales; \
    update-locale LANG=ko_KR.UTF-8; \
    apt clean && rm -rf /var/lib/apt/lists/* /tmp/*

ENV LANG ko_KR.UTF-8

ENV GOSU_VERSION=1.16

RUN set -eux; \
    savedAptMark="$(apt-mark showmanual)"; \
    apt-get update; \
    apt-get install -y --no-install-recommends ca-certificates wget; \
    rm -rf /var/lib/apt/lists/*; \
    dpkgArch="$(dpkg --print-architecture | awk -F- '{ print $NF }')"; \
    wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch"; \
    wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch.asc"; \
    export GNUPGHOME="$(mktemp -d)"; \
    gpg --batch --keyserver hkps://keys.openpgp.org --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4; \
    gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu; \
    gpgconf --kill all; \
    rm -rf "$GNUPGHOME" /usr/local/bin/gosu.asc; \
    apt-mark auto '.*' > /dev/null; \
    [ -z "$savedAptMark" ] || apt-mark manual $savedAptMark > /dev/null; \
    apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \
    chmod +x /usr/local/bin/gosu; \
    gosu --version; \
    gosu nobody true

RUN set -eux; \
    key='859BE8D7C586F538430B19C2467B942D3A79BD29'; \
    export GNUPGHOME="$(mktemp -d)"; \
    gpg --batch --keyserver keyserver.ubuntu.com --recv-keys "$key"; \
    mkdir -p /etc/apt/keyrings; \
    gpg --batch --export "$key" > /etc/apt/keyrings/mysql.gpg; \
    gpgconf --kill all; \
    rm -rf "$GNUPGHOME"

ADD deb /deb

RUN apt install -y /deb/mysql-apt-config_0.8.25-1_all.deb; \
    apt update -y; \
    apt install -y --no-install-recommends mysql-server; \
    apt clean; \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN mkdir -p /docker-entrypoint-initdb.d /var/lib/mysql /var/run/mysqld; \
    chown -R mysql:mysql /var/lib/mysql /var/run/mysqld; \
    chmod 1777 /var/run/mysqld /var/lib/mysql

VOLUME /var/lib/mysql

COPY config/ /etc/mysql/

COPY docker-entrypoint.sh /usr/local/bin/

RUN chmod 755 /usr/local/bin/docker-entrypoint.sh

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]

EXPOSE 3306 33060

CMD ["mysqld"]
